x-superset-image: &superset-image apachesuperset.docker.scarf.sh/apache/superset:6.0.0
x-superset-user: &superset-user root
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes: &superset-volumes
  - ./docker:/app/docker
  - ./superset_config.py:/app/pythonpath/superset_config.py
  - superset_home:/app/superset_home

services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    env_file: .env
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - superset_db_home:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 3

  superset:
    env_file: .env
    image: *superset-image
    container_name: superset_app
    command: ["bash", "/app/docker/docker-bootstrap.sh", "app"]
    user: *superset-user
    ports:
      - "8088:8088"
    volumes: *superset-volumes
    depends_on: *superset-depends-on
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  superset-worker:
    env_file: .env
    image: *superset-image
    container_name: superset_worker
    command: ["bash", "/app/docker/docker-bootstrap.sh", "worker"]
    user: *superset-user
    restart: unless-stopped
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    healthcheck:
      disable: true

  superset-worker-beat:
    env_file: .env
    image: *superset-image
    container_name: superset_worker_beat
    command: ["bash", "/app/docker/docker-bootstrap.sh", "beat"]
    user: *superset-user
    restart: unless-stopped
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    healthcheck:
      disable: true

  postgresqlv2:
    image: postgres:15
    container_name: postgresqlv2
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "APSLab"
      POSTGRES_DB: mosfets
    shm_size: 128G
    volumes:
      - postgresqlv2_data:/var/lib/postgresql/data
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  superset_home:
    external: true
    name: superset_superset_home
  superset_db_home:
    external: true
    name: superset_db_home
  postgresqlv2_data:
    external: true
    name: superset_postgresqlv2_data
